### ISSUE TITLE
module name does not match file path by any convention

### ISSUE THREAD

**Issue by e2** [imathis/guard-jekyll-plus#33]
expected: `guard/jekyll_plus{.rb,/**{` and `module Guard::JekyllPlus`
actual: `guard/jekyll-plus{.rb,/**}` and `module Guard::Jekyllplus`

acceptable alternative: `guard/jekyllplus{.rb,/**}` and `module Guard::Jekyllplus`

Problem: mostly with the template (`guard init`), although both Guard and plugins should adopt a single convention (and deprecate everything else).

Reference: http://guides.rubygems.org/name-your-gem/

It's up to you to decide whether you want to change the module name or the file names - if you make the changes and commit to master, I'll make sure they work in Guard.

**Comment by imathis** [comment]
Thanks for your help with this. If I rename the module, doesn't that also mean I'd have to rename the gem? Last time I remember trying to get Guard to find the files, I remember it being troublesome to get the Gem and Guard to both to read the correct folder.

**Comment by e2** [comment]
> Thanks for your help with this.

No prob - Guard doesn't give a good error message when this fails, so it's about time I cleaned up this confusion.

> If I rename the module, doesn't that also mean I'd have to rename the gem?

Well, ideally yes e.g. guard-jekyll_plus or guard-jekyllplus) - but that's only to match the Rubygems convention.

Guard doesn't care about the gem name (AFAIK), because that's the Gemfile's responsibility, not Guard's.

The current gem name suggests the module Guard::Jekyll::Plus exists - so it's up to you if you want to fix that or not. (There's RuboCop which uses 'rubocop' instead of 'rubo_cop').

I currently just want to get requiring the plugin and template generating to work in a single "recommended" way (and document it).

So I basically care just about the file names matching the module name (at this point at least).

> Last time I remember trying to get Guard to find the files, I remember it being troublesome to get the Gem and Guard to both to read the correct folder.

Yeah - I can see why, and I saw that you made changes in the past. I want to clean this up, because the mess was cause by Guard::LiveReload ( which uses 'livereload.rb') and Guard::JekyllPlus took the hit ...

I'm also not sure about the guard name, e.g.:
- `guard :jekyll-plus` won't work (subtraction)
- `guard 'jekyll-plus'` should be fine
- `guard ':jekyll_plus'` could work too
- `guard ':jekyllplus'` would be ok (if you use Jekyllplus)

Anyway, I just want to give you a heads up - I don't want to cause any disruption, and if you get the modulename and files matching Rubygems convention, let me know and I'll make sure it works (and let you know for a release).

If you have any suggestions, let me know. (Overall it's "cleaner" for guard to remove dashes and underscores inside filenames instead of adding them - so even JekylPlus with 'jekyllplus.rb' is fine with me).

**Comment by e2** [comment]
This is related: https://github.com/guard/guard/issues/721

In a nutshell, you should:
1) decide on a "human friendly" project name ("Jekyll Plus" or "JekyllPlus" or "Jekyll::Plus" or whatever)
2) decide on a module name (Jekyllplus or JekyllPlus or Jekyll::Plus) which fits best
3) fix the paths to match the RubyGems convention for the module name
4) optionally change the gem name (I don't care - because people specify it through bundler)

It's your project, so you have to decide on 1 and you have to pick something "reasonable" for 2.

(I can't help you until you decide on those)

**Comment by imathis** [comment]
Thanks for all the explanation! I'll work on fixing this up tomorrow.

**Comment by e2** [comment]
:+1:
