### ISSUE TITLE
Error - Guard Jekyll Plus in Windows 8.1

### ISSUE THREAD

**Issue by prbrazildev** [imathis/guard-jekyll-plus#43]
C:\Users\pauloandrade\Documents\projetos\prba>guard
Configuration file: _config.yml
11:27:46 - INFO - Jekyll building...
11:27:48 - INFO - Jekyll build completed in 1.72s C:/Users/pauloandrade/Document
s/projetos/prba ÔåÆ _site
11:27:48 - ERROR - Guard::JekyllPlus failed to achieve its <start>, exception wa
s:

> [#145D4DF2C363] NotImplementedError: fork() function is unimplemented on this
> machine
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-jekyll-plus-2.0.2/l
> ib/guard/jekyll_plus/server.rb:68:in `fork'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-jekyll-plus-2.0.2/l
> ib/guard/jekyll_plus/server.rb:68:in`start_jekyll'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-jekyll-plus-2.0.2/l
> ib/guard/jekyll_plus/server.rb:18:in `start'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-jekyll-plus-2.0.2/l
> ib/guard/jekyll_plus.rb:25:in`start'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:82:in `block in _supervise'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:79:in`catch'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:79:in `_supervise'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:22:in`block (3 levels) in run'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:119:in `block (2 levels) in _run_group_plugins'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:117:in`each'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:117:in `block in _run_group_plugins'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:116:in`catch'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:116:in `_run_group_plugins'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:21:in`block (2 levels) in run'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:20:in `each'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:20:in`block in run'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/lumberjack-1.0.9/lib/lumb
> erjack.rb:32:in `unit_of_work'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ru
> nner.rb:18:in`run'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/co
> mmander.rb:34:in `start'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/cl
> i/environments/valid.rb:16:in`start_guard'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/cl
> i.rb:122:in `start'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/comm
> and.rb:27:in`run'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invo
> cation.rb:126:in `invoke_command'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:3
> 59:in`dispatch'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base
> .rb:440:in `start'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ar
> uba_adapter.rb:32:in`execute'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/lib/guard/ar
> uba_adapter.rb:19:in `execute!'
> [#145D4DF2C363] C:/App/Ruby/lib/ruby/gems/2.0.0/gems/guard-2.12.6/bin/_guard-c
> ore:11:in`<main>'
> 11:27:48 - INFO - Guard::JekyllPlus has just been fired
> 11:27:48 - INFO - Guard is now watching at 'C:/Users/pauloandrade/Documents/proj
> etos/prba'
> [1] guard(main)> ]

How I do solve this?

**Comment by e2** [comment]
> [#145D4DF2C363] NotImplementedError: fork() function is unimplemented on this
> machine

Windows does not support the Linux/Unix/OSX `fork()` method used by Jekyll server. 

You'll need a "threaded server" like `thin`, so use a rack config (see the README here: https://github.com/imathis/guard-jekyll-plus#using-rack-server).
